name: cryptoscan_pro
description: CryptoScan Pro - Gerçek zamanlı kripto tarama uygulaması
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.4.1
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  google_mobile_ads: ^2.3.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
