name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release --no-shrink

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: CryptoScanPro.apk
          path: build/app/outputs/flutter-apk/app-release.apk
